Check for duplicate incident before adding to database
BloomTech-Labs/dep-human-rights-first-be-a pull request #11
Opened 2020-11-13 21:42 UTC by jduell12

# Description
Fixes the issue where the checking for duplicates functionality was allowing duplicates through. Added function to add the state abbreviation to each incident per front end request. 

## Type of change
Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Change Status
- Complete, tested, ready to review and merge

# How Has This Been Tested?
- Jest

2020-11-13 21:46 UTC, tonomb commented on api/incidents/incidentsModel.js
> +async function showAllIncidents(limit = 10, offset = 0) {
Doesn't this add a default value to limit and offset?  What happens if you what to get all the data?

2020-11-13 21:47 UTC, tonomb requested changes
I just have douts about the defaults for limit and offset, Otherwise looks great!!!

2020-11-13 21:53 UTC, jduell12 commented on api/incidents/incidentsModel.js
> +async function showAllIncidents(limit = 10, offset = 0) {
I have to set some default value for limit otherwise if nothing is passed it throws an error. I could also get the length of the current db and use that as a default limit.

2020-11-14 00:07 UTC, jduell12 commented on api/incidents/incidentsModel.js
> +async function showAllIncidents(limit = 10, offset = 0) {
Running some more tests I can't put None or null as the default value. Leaving the default blank while console logging an error doesn't seem to actually break the server tests. I took the default limit out and if needed we can add it back in or create another endpoint that doesn't have a limit or offset.

2020-11-14 00:08 UTC, merged